/* eslint-disable react-refresh/only-export-components */
export const GET_COUNTRIES = 'GET_COUNTRIES'
export const GET_DETAIL = 'GET_DETAIL'
export const POST_ACTIVITY = 'POST_ACTIVITY'
export const GET_ACTIVITIES = 'GET_ACTIVITIES'
export const FILTER = 'FILTER'
export const ORDER = 'ORDER'
export const FILTER_ACTIVITIES = 'FILTER_ACTIVITIES'
export const ORDER_ACTIVITIES = 'ORDER_ACTIVITIES'
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY'
export const ERROR = 'ERROR'
export const SEARCH = 'SEARCH'
export const CLEAN_DETAIL = 'CLEAN_DETAIL'
export const CLEAN_ALL = 'CLEAN_ALL'
export const CLEAN_ACTIVITY_FILTERS = 'CLEAN_ACTIVITY_FILTERS'